
const EDUCATION = [
    { key:0,
      title:'find determinant',
      time:'30 min',
      Message : 'medium',
      image: require('../../assets/edu.jpg'),
      link:'rqZEWmWy1hQ',
    },
    { key:1,
      title:'integration',
      time:'20 min',
      Message : 'hard',
      image: require('../../assets/edu.jpg'),
      link:'rqZEWmWy1hQ',
    },
    { key:2,
      title:'Multiplication',
      time:'13 min',
      Message : 'easy',
      image: require('../../assets/edu.jpg'),
      link:'rqZEWmWy1hQ',
    },
    { key:3,
        title:'Multiplication',
        time:'13 min',
        Message : 'easy',
        image: require('../../assets/edu.jpg'),
        link:'rqZEWmWy1hQ',
      },
      { key:4,
        title:'Multiplication',
        time:'13 min',
        Message : 'easy',
        image: require('../../assets/edu.jpg'),
        link:'rqZEWmWy1hQ',
      },
  ];

  const HEALTH = [
    { key:0,
      title:'CPR',
      time:'5 min',
      Message : 'easy',
      image: require('../../assets/hp1.jpg'),
      link:'rqZEWmWy1hQ',
    },
    { key:1,
      title:'First Aid',
      time:'10 min',
      Message : 'hard',
      image: require('../../assets/hp1.jpg'),
      link:'rqZEWmWy1hQ',
    },
    { key:2,
      title:'Meds',
      time:'20 min',
      Message : 'hard',
      image: require('../../assets/hp1.jpg'),
      link:'rqZEWmWy1hQ',
    },
  ];

  const COOKING = [
    { key:0,
      title:'veg',
      time:'30 min',
      Message : 'medium',
      image: require('../../assets/cook1.jpeg'),
      link:'rqZEWmWy1hQ',
    },
    { key:1,
      title:'meat',
      time:'20 min',
      Message : 'hard',
      image: require('../../assets/cook1.jpeg'),
      link:'rqZEWmWy1hQ',
    },
    { key:2,
      title:'utensils',
      time:'13 min',
      Message : 'easy',
      image: require('../../assets/cook1.jpeg'),
      link:'rqZEWmWy1hQ',
    },
  ];

  const EXERCISES = [
    { key:0,
      title:'dumbell',
      time:'30 min',
      Message : 'hard',
      image: require('../../assets/exer1.png'),
      link:'rqZEWmWy1hQ',
    },
    { key:1,
      title:'pushup',
      time:'20 min',
      Message : 'medium',
      image: require('../../assets/exer1.png'),
      link:'rqZEWmWy1hQ',
    },
    { key:2,
      title:'plank',
      time:'13 min',
      Message : 'easy',
      image: require('../../assets/exer1.png'),
      link:'rqZEWmWy1hQ',
    },
  ];

  export { EDUCATION, COOKING, HEALTH, EXERCISES };